import { StripeWebhookController } from "../../api/controllers/sripeWebhook";

const TYPES = {
  Config: Symbol.for("Config"),

  AuthRepository: Symbol.for("AuthRepository"),
  CustomerRepository: Symbol.for("CustomerRepository"),
  OtpRepository: Symbol.for("OtpRepository"),
  ClientRepository: Symbol.for("ClientRepository"),
  ClientAttachmentRepository: Symbol.for("ClientAttachmentRepository"),
  PaymentRepository: Symbol.for("PaymentRepository"),
  ReservationRepository: Symbol.for("ReservationRepository"),
  EmployeeRepository: Symbol.for("EmployeeRepository"),
  EmployeeImageRepository: Symbol.for("EmployeeImageRepository"),
  IProductRepository: Symbol.for("IProductRepository"),
  IProductImageRepository: Symbol.for("IProductImageRepository"),
  IProductRatingRepository: Symbol.for("IProductRatingRepository"),
  IShapeRepository: Symbol.for("IShapeRepository"),
  IFlavorRepository: Symbol.for("IFlavorRepository"),
  IMaskRepository: Symbol.for("IMaskRepository"),
  IFinalProductRepository: Symbol.for("IFinalProductRepository"),

  ProductRepository: Symbol.for("ProductRepository"),
  ProductImageRepository: Symbol.for("ProductImageRepository"),
  ProductRatingRepository: Symbol.for("ProductRatingRepository"),
  ShapeRepository: Symbol.for("ShapeRepository"),
  FlavorRepository: Symbol.for("FlavorRepository"),
  MaskRepository: Symbol.for("MaskRepository"),
  FinalProductRepository: Symbol.for("FinalProductRepository"),

  DeviceTokenRepository: Symbol.for("DeviceTokenRepository"),
  TicketRepository: Symbol.for("TicketRepository"),
  TicketMessageRepository: Symbol.for("TicketMessageRepository"),

  AuthService: Symbol.for("AuthService"),
  CustomerService: Symbol.for("CustomerService"),
  SmsService: Symbol.for("SmsService"),
  ClientService: Symbol.for("ClientService"),
  EmployeeService: Symbol.for("EmployeeService"),
  ProductService: Symbol.for("ProductService"),
  ShapeService: Symbol.for("ShapeService"),
  FlavorService: Symbol.for("FlavorService"),
  MaskService: Symbol.for("MaskService"),
  FinalProductService: Symbol.for("FinalProductService"),
  TamaraService: Symbol.for("TamaraService"),
  MimoService: Symbol.for("MimoService"),
  NotificationService: Symbol.for("NotificationService"),
  TicketMessageService: Symbol.for("TicketMessageService"),
  TicketService: Symbol.for("TicketService"),
  SummaryService: Symbol.for("SummaryService"),
  PaymentService: Symbol.for("PaymentService"),
  IReservationService: Symbol.for("IReservationService"),
  ReservationService: Symbol.for("ReservationService"),
  ReservationPaymentService: Symbol.for("ReservationPaymentService"),

  AuthController: Symbol.for("AuthController"),
  CustomerController: Symbol.for("CustomerController"),
  ClientController: Symbol.for("ClientController"),
  EmployeeController: Symbol.for("EmployeeController"),
  ProductController: Symbol.for("ProductController"),
  ShapeController: Symbol.for("ShapeController"),
  FlavorController: Symbol.for("FlavorController"),
  MaskController: Symbol.for("MaskController"),
  FinalProductController: Symbol.for("FinalProductController"),
  TicketController: Symbol.for("TicketController"),
  SummaryController: Symbol.for("SummaryController"),
  MimoController: Symbol.for("MimoController"),
  MimoWebhookController: Symbol.for("MimoWebhookController"),
  PaymentController: Symbol.for("PaymentController"),
  ReservationController: Symbol.for("ReservationController"),
  DeviceTokenController: Symbol.for("DeviceTokenController "),
  TamaraController: Symbol.for("TamaraController"),
  TamaraWebhookController: Symbol.for("TamaraWebhookController"),
  StripeWebhookController: Symbol.for("StripeWebhookController"),

  PhoneStrategy: Symbol.for("PhoneStrategy"),

  CustomerRoutes: Symbol.for("CustomerRoutes"),
  ClientRoutes: Symbol.for("ClientRoutes"),
  EmployeeRoutes: Symbol.for("EmployeeRoutes"),
  ProductRoutes: Symbol.for("ProductRoutes"),
  ShapeRoutes: Symbol.for("ShapeRoutes"),
  FlavorRoutes: Symbol.for("FlavorRoutes"),
  MaskRoutes: Symbol.for("MaskRoutes"),
  FinalProductRoutes: Symbol.for("FinalProductRoutes"),
  ReservationRoutes: Symbol.for("ReservationRoutes"),
  TicketRoutes: Symbol.for("TicketRoutes"),
  PaymentRoutes: Symbol.for("PaymentRoutes"),
  SummaryRoutes: Symbol.for("SummaryRoutes"),
  DeviceTokenRoutes: Symbol.for("DeviceTokenRoutes"),
  TamaraRoutes: Symbol.for("TamaraRoutes"),
  MimoRoutes: Symbol.for("MimoRoutes"),
  StripeService: Symbol.for("StripeService"),
  StripeController: Symbol.for("StripeController"),
  StripeRoutes: Symbol.for("StripeRoutes"),

  Logger: Symbol.for("Logger"),
};

export { TYPES };
